"""Generate SVG geometry: python3 scripts/generate-europe-map.py source.geojson.
Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_admin_0_countries.geojson
Natural Earth 1:50m, public domain. Boundaries reflect the source dataset.
Projection: equirectangular, standard parallel 54 degrees; bounds 25W–46E, 32N–82N.
"""
import json, math, sys
from pathlib import Path

CAPITALS = {
'SJ':(15.63,78.22),'IS':(-21.94,64.15),'NO':(10.75,59.91),'SE':(18.07,59.33),
'FI':(24.94,60.17),'DK':(12.57,55.68),'GB':(-0.13,51.51),'IE':(-6.26,53.35),
'NL':(4.90,52.37),'BE':(4.35,50.85),'FR':(2.35,48.86),'ES':(-3.70,40.42),
'PT':(-9.14,38.72),'DE':(13.40,52.52),'CH':(7.45,46.95),'AT':(16.37,48.21),
'IT':(12.50,41.90),'PL':(21.01,52.23),'CZ':(14.42,50.08),'SK':(17.11,48.15),
'HU':(19.04,47.50),'EE':(24.75,59.44),'LV':(24.11,56.95),'LT':(25.28,54.69),
'BY':(27.56,53.90),'UA':(30.52,50.45),'MD':(28.83,47.01),'RO':(26.10,44.43),
'SI':(14.51,46.06),'HR':(15.98,45.81),'BA':(18.41,43.86),'RS':(20.46,44.82),
'BG':(23.32,42.70),'AL':(19.82,41.33),'MK':(21.43,42.00),'GR':(23.73,37.98),
'TR':(32.86,39.93)}

def project(point):
    lon,lat=point
    return round(64+(lon+25)*18*math.cos(math.radians(54)),2),round(40+(82-lat)*18,2)

def clip(points):
    for axis,edge,sign in [(0,-25,1),(0,46,-1),(1,32,1),(1,82,-1)]:
        output=[]
        for a,b in zip(points[-1:]+points[:-1],points):
            ain=(a[axis]-edge)*sign>=0; bin=(b[axis]-edge)*sign>=0
            if ain != bin:
                t=(edge-a[axis])/(b[axis]-a[axis])
                output.append([a[0]+t*(b[0]-a[0]),a[1]+t*(b[1]-a[1])])
            if bin: output.append(b)
        points=output
    return points

features=json.loads(Path(sys.argv[1]).read_text())['features']
paths={}; background=[]
for feature in features:
    code=feature['properties']['ISO_A2_EH']
    geometry=feature['geometry']
    polygons=geometry['coordinates'] if geometry['type']=='MultiPolygon' else [geometry['coordinates']]
    for polygon in polygons:
        # Svalbard is part of Norway in the source; keep its existing separate checkpoint.
        target='SJ' if code=='NO' and min(p[1] for p in polygon[0])>74 else code
        rings=[]
        for ring in polygon:
            points=clip(ring)
            if len(points)<3: continue
            coords=[project(p) for p in points]
            rings.append('M'+'L'.join(f'{x},{y}' for x,y in coords)+'Z')
        if rings:
            path=''.join(rings)
            if target in CAPITALS: paths.setdefault(target,[]).append(path)
            else: background.append(path)
assert set(paths)==set(CAPITALS), set(CAPITALS)-set(paths)
result={code:{'path':''.join(parts),'cx':project(CAPITALS[code])[0],'cy':project(CAPITALS[code])[1]} for code,parts in paths.items()}
Path('src/data/europeGeometry.ts').write_text('// Generated by scripts/generate-europe-map.py. Natural Earth, public domain.\nexport const EUROPE_GEOMETRY: Record<string, { path: string; cx: number; cy: number }> = '+json.dumps(result,separators=(',',':'))+';\nexport const EUROPE_BACKGROUND_PATH = '+json.dumps(''.join(background))+';\n')
print(f'Generated {len(result)} mapped countries and territories.')
